services:
  ogs-server:
    image: ogs-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ogs-server
    hostname: ogs-server
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/bus/usb:/dev/bus/usb"
    command: flask run --host=ogs-server --port=5000
